repos:
  - repo: local
    hooks:

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        stages: [commit]

      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types: [python]
        stages: [commit]
