repos:
  - repo: local
    hooks:

      - id: ruff
        name: ruff
        entry: ruff check --fix
        language: python
        types: [python]
        stages: [pre-commit]
        always_run: true

      - id: black
        name: black
        entry: black .
        language: python
        types: [python]
        stages: [pre-commit]
        always_run: true


