# Generated by Django 5.2.6 on 2025-09-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="company_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="feedback",
            name="sender_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["company_name"], name="feedback_company_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["sender_name"], name="feedback_sender_idx"),
        ),
    ]
