name: Tests on pull request
run-name: Testing code

on: 
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

jobs:

  run_django_tests:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
      DEBUG: ${{ secrets.DEBUG }}
    strategy:
      max-parallel: 4
      matrix:
        python_version: [3.12.3]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: MY SECRETS
        run: |
          echo 'SECRET_KEY is ${{ secrets.SECRET_KEY }}'
          echo 'DJANGO_ALLOWED_HOSTS is ${{ secrets.DJANGO_ALLOWED_HOSTS }}'
          echo 'DEBUG is ${{ secrets.DEBUG }}'
      
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: | 
          cd app/backend
          export PATH="$HOME/.local/bin:$PATH"
          uv sync
          uv cache prune --ci
        
      - name: Run Django tests
        run: |
          cd app/backend
          source .venv/bin/activate

          cd django
          python manage.py test


